services:
  alunmos_db:
    container_name: alunmos_db
    image: postgres:17.2
    restart: always
    volumes:
    - ./back-end/postgres:/var/lib/postgresql/data
    ports:
    - 5435:5432
    environment:
      POSTGRES_USER: tuchance
      POSTGRES_PASSWORD: tuchance123
      POSTGRES_DB: alunmos_db
  backend:
    depends_on:
      - alunmos_db
    build: 
     context: ./back-end
     dockerfile: dockerfile
    volumes:
      - ./back-end/src:/usr/src/app/src
    command: npm run dev
    ports:
      - ${PORT}:$PORT
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - API_KEY=${API_KEY}